pip install -U pip
pip install -U scipy
pip install -U matplotlib
pip install -U PySimpleGUI
pip install -U astropy
pip install -U opencv-python
pip install -U lsq-ellipse
pip install -U scikit-image
pip install -U pillow
